### ISSUE TITLE
Search listener unresponsive to non-alphanumeric characters

### ISSUE THREAD

**Issue by athousandleaves** [gabeotisbenson/rt_lite#7]
I dig your site! One thing I noticed though, is that your search listener is unresponsive if you try to search for a title with a non-alphanumeric character (Ex.: _Starsky & Hutch_).

**Comment by gabeotisbenson** [comment]
Just fixed this issue with commit [d8e24b4](https://github.com/gabeotisbenson/rt_lite/commit/d8e24b49d78aff8501d699b5b2b8830bfcbc4a3b)
